config/routes.rb
Rails.application.routes.draw do
  rutarel = ENV.fetch('RUTA_RELATIVA', 'multiplesanexos/')
  scope rutarel do
    devise_scope :usuario do
      get 'sign_out' => 'devise/sessions#destroy'
      if (Rails.configuration.relative_url_root != '/')
        ruta = File.join(Rails.configuration.relative_url_root,
                         'usuarios/sign_in')
        post ruta, to: 'devise/sessions#create'
        get  ruta, to: 'devise/sessions#new'
      end
    end

    devise_for :usuarios, :skip => [:registrations], module: :devise
    as :usuario do
      get 'usuarios/edit' => 'devise/registrations#edit',
        :as => 'editar_registro_usuario'
      put 'usuarios/:id' => 'devise/registrations#update',
        :as => 'registro_usuario'
    end
    resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' }

    root 'sip/hogar#index'
  end  # scope
  mount Sip::Engine, at: rutarel, as: 'sip'
end

app/models/ability.rb
class Ability  < Sip::Ability


  # Se definen habilidades con cancancan
  # @usuario Usuario que hace petición
  def initialize(usuario = nil)
    # El primer argumento para can es la acción a la que se da permiso,
    # el segundo es el recurso sobre el que puede realizar la acción,
    # el tercero opcional es un diccionario de condiciones para filtrar
    # más (e.g :publicado => true).
    #
    # El primer argumento puede ser :manage para indicar toda acción,
    # o grupos de acciones como :read (incluye :show e :index),
    # :create, :update y :destroy.
    #
    # Si como segundo argumento usa :all se aplica a todo recurso,
    # o puede ser una clase.
    #
    # Detalles en el wiki de cancan:
    #   https://github.com/ryanb/cancan/wiki/Defining-Abilities


    # Sin autenticación puede consultarse información geográfica
    can :read, [Sip::Pais, Sip::Departamento, Sip::Municipio, Sip::Clase]
    # No se autorizan usuarios con fecha de deshabilitación
    if !usuario || usuario.fechadeshabilitacion
      return
    end
    can :contar, Sip::Ubicacion
    can :buscar, Sip::Ubicacion
    can :lista, Sip::Ubicacion
    can :descarga_anexo, Sip::Anexo
    can :nuevo, Sip::Ubicacion
    if usuario && usuario.rol then
      case usuario.rol
      when Ability::ROLANALI
        can :read, Sip::Orgsocial
        can :read, Sip::Persona
        can :read, Sip::Ubicacion
        can :new, Sip::Ubicacion
        can [:update, :create, :destroy], Sip::Ubicacion
      when Ability::ROLADMIN
        can :manage, Sip::Orgsocial
        can :manage, Sip::Persona
        can :manage, Sip::Respaldo7z
        can :manage, Sip::Ubicacion
        can :manage, ::Usuario
        can :manage, :tablasbasicas
        self.tablasbasicas.each do |t|
          c = Ability.tb_clase(t)
          can :manage, c
        end
      end
    end
  end # def initialize

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sip/anexo.rb
require 'sip/concerns/models/anexo'

module Sip
  class Anexo < ActiveRecord::Base

    has_many :anexo_persona, foreign_key: :anexo_id,
      validate: true, class_name: 'Sip::AnexoPersona'
    has_many :persona, class_name: 'Sip::Persona', through: :anexo_persona

  end
end

app/models/sip/anexo_persona.rb
module Sip
  class AnexoPersona < ActiveRecord::Base

    belongs_to :persona, foreign_key: :persona_id,
      class_name: 'Sip::Persona'
    belongs_to :anexo, foreign_key: :anexo_id,
      class_name: 'Sip::Anexo'

    accepts_nested_attributes_for :anexo, reject_if: :all_blank

    validates :persona, presence: true
    validates :anexo, presence: true
  end
end

app/models/sip/persona.rb
require 'sip/concerns/models/persona'

module Sip
  class Persona < ActiveRecord::Base
    include Sip::Concerns::Models::Persona

    has_many :anexo_persona, dependent: :delete_all,
      class_name: 'Sip::AnexoPersona',
      foreign_key: 'persona_id', validate: true
    accepts_nested_attributes_for :anexo_persona, 
      allow_destroy: true, reject_if: :all_blank
    has_many :sip_anexo, :through => :anexo_persona, 
      class_name: 'Sip::Anexo'
    accepts_nested_attributes_for :sip_anexo,  reject_if: :all_blank

  end
end

app/models/usuario.rb
require 'sip/concerns/models/usuario'

class Usuario < ActiveRecord::Base
  include Sip::Concerns::Models::Usuario
end

app/controllers/application_controller.rb
require 'sip/application_controller'
class ApplicationController < Sip::ApplicationController
  # Previente ataques CSRF elevando una excepción
  # En el caso de APIs, en cambio puedes querer usar :null_session
  protect_from_forgery with: :exception
end

app/controllers/sip/personas_controller.rb
require 'sip/concerns/controllers/personas_controller'

module Sip
  class PersonasController < Sip::ModelosController

    load_and_authorize_resource class: Sip::Persona

    include Sip::Concerns::Controllers::PersonasController

   
    def atributos_show
      self.atributos_show_sip +
        [:anexos]
    end


    def lista_params
      lista_params_sip + [
        anexo_persona_attributes: [
          :id, 
          :persona_id,
          :_destroy,
          anexo_attributes: [
            :id, 
            :descripcion, 
            :adjunto, 
            :_destroy
          ]
        ]
      ]
    end

  end
end

app/controllers/usuarios_controller.rb
require 'sip/concerns/controllers/usuarios_controller'

class UsuariosController < Sip::ModelosController
  include Sip::Concerns::Controllers::UsuariosController

  def index
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Sip::BootstrapHelper
end

app/views/layouts/application.html.erb
<% content_for :titulo do %>
    <%= Sip.titulo %>
<% end %>

<% content_for :menu do %>
   <%= grupo_menus do %>
    <% if !current_usuario.nil? %>
        <%= opcion_menu "Organizaciones sociales", sip.orgsociales_path %>
        <%= opcion_menu "Personas", sip.personas_path %>
    <% end %>
  <% end %>
  <%= grupo_menus :empuja => :derecha do %>
    <%= opcion_menu "Documentacion", "https://github.com/pasosdeJesus/sip/tree/master/doc/README.md" %>
    <% if current_usuario %>
      <%= despliega_abajo "Administrar" do %>
        <%= opcion_menu "Clave", main_app.editar_registro_usuario_path, desplegable: true %>
        <%= opcion_menu "Copia de respaldo cifrada", sip.respaldo7z_path, desplegable: true %>
        <%= opcion_menu "Usuarios", main_app.usuarios_path, desplegable: true %>
        <%= opcion_menu "Tablas Básicas", sip.tablasbasicas_path, desplegable: true %>
        <%= opcion_menu "Ayuda CA", sip.ayuda_controldeacceso_path, desplegable: true %>
      <% end %>
      <%= opcion_menu "Salir #{current_usuario.nusuario}", main_app.sign_out_path %>
    <% else %>
      <%= opcion_menu "Acerca de", sip.acercade_path %>
      <%= opcion_menu "Iniciar Sesión", main_app.new_usuario_session_path %>
    <% end %>
  <% end %>
<% end %>

<% content_for :piedepagina do %>
  <p><span class='derechos'><a href="https://www.pasosdejesus.org/dominio_publico_colombia.html">Dominio Público de acuerdo a Legislación Colombiana</a><br/>
    Desarrollado por <a href="https://www.pasosdeJesus.org" target="_blank">Pasos de Jesús</a>. 2022.
  </span></p>
<% end %>

<%= render template: "layouts/sip/application" %>

app/views/sip/anexos/_anexosinsip_campos.html.erb
<%= a.input :descripcion %>
<% if !a.object || !a.object.adjunto_file_name || !a.object.id %>
  <%= a.input :adjunto, as: :file, label: t('Archivo') %>
<% else %>
  <div class="anexo_adjunto">
    <label for="anexo_attributes_<%=a.object.id%>_adjunto"><%= t('Archivo') %></label>
    <a id="anexo_attributes_<%=a.object.id%>_adjunto" href="<%= sip.descarga_anexo_path(a.object.id) %>", style="text-decoration:none" data-turbo='false'><%= a.object.adjunto_file_name %></a>
  </div>
<% end %>
<%= a.input :id, as: :hidden %>

app/views/sip/anexos/_anexosinsip_campos_condiv.html.erb
<div class='control-group nested-fields'>
  <div class="controls">

    <%  f.object.anexo = Sip::Anexo.new if !f.object.anexo %>

    <%= f.simple_fields_for :anexo do |a| %>
      <%= render 'sip/anexos/anexosinsip_campos', a: a %>
    <% end %>

    <%= link_to_remove_association "Eliminar Anexo", f, 
      :class => 'btn-danger' 
    %> 
  </div>
</div>

app/views/sip/personas/_campo_anexos.html.erb
<div class='accordion' id="acordeon_secanexos">
  <%= item_acordeon_bs(
    'acordeon_secanexos', 'secanexos', 
    t('Medios de verificación / Anexos'), false, {
      'estilo_accordion-header' => 'text-align: center',
      'estilo_accordion-body' => 'anexos-div anexosdiv'
    })  do %>
    <% if f.object.id.nil? %>
      Guarde esta persona para poder agregarle anexos
    <% else %>
      <%= f.simple_fields_for :anexo_persona do |ap| %>
        <%= render 'sip/anexos/anexosinsip_campos_condiv', :f => ap %>
      <% end %>
    <% end %>
  <% end %>
  <div class="links">
    <%= link_to_add_association t('Añadir anexo'), f, 
      :anexo_persona, :class => 'btn-primary',
      partial: 'sip/anexos/anexosinsip_campos_condiv'
    %>
  </div>
</div> <!-- accordion -->